### ISSUE TITLE
Question about which errors to report

### ISSUE THREAD

**Issue by AndyDangerous** [bigcommerce/gruf-sentry#6]
Hi! I have a question about how to use this gem correctly. I am using gruf as a standalone framework (i.e. without Rails), and am using Sentry for error reporting. Right now, this interceptor works great for errors generated on the grpc side of my application, but ignores errors stemming from the business logic. 

I am wondering if I am using this gem/interceptor incorrectly or if there is another way that you would recommend for sending my errors to Sentry. I am happy to fork this repo and make it report all errors vs. using the allowlist. I could also open a PR to allow the interceptor to be configured to report all errors to Sentry, if that would be helpful to other folks.

**Comment by splittingred** [comment]
Hello @AndyDangerous!

gruf-sentry _only_ captures uncaught exceptions in Gruf controllers or Gruf::Client calls, and pushes them to Sentry. It does not automatically instrument any business logic inside for you - for that, I would look at Sentry's docs on how to instrument things: https://docs.sentry.io/platforms/ruby/usage/

Thanks!
